<?php

namespace AppBundle\Repository;

/**
 * Shop_orderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Shop_orderRepository extends \Doctrine\ORM\EntityRepository {
}
