# src/AppBundle/Resources/config/routing.yml

homepage:
    path:   /
    defaults: { _controller: AppBundle:Default:show }

ticket_show:
    path:   /ticket
    defaults: { _controller: AppBundle:Ticket:show }
