# src/AppBundle/Resources/config/routing.yml

homepage:
    path:   /
    defaults: { _controller: AppBundle:Order:show }
validate:
    path: /validate
    defaults: { _controller: AppBundle:Order:validateUserTickets }
